[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "      default-src 'self';\n      style-src 'self' https://rsms.me 'unsafe-inline';\n      script-src 'self';\n      connect-src 'self' https://backend-portfolio-production-1a2f.up.railway.app;\n      font-src 'self' https://rsms.me;\n    "

[build]
command = "npx vite build"
publish = "dist"